import { Genre } from '@type/Genre';

export const GENRES: Genre[] = [
  { label: '액션', id: 'action' },
  { label: '판타지', id: 'fantasy' },
  { label: 'SF', id: 'sf' },
  { label: '스릴러', id: 'thriller' },
  { label: '미스터리', id: 'mystery' },
  { label: '어드벤처', id: 'adventure' },
  { label: '뮤지컬', id: 'musical' },
  { label: '코미디', id: 'comedy' },
  { label: '서부극', id: 'western' },
  { label: '멜로/로맨스', id: 'romance' },
  { label: '서사/드라마', id: 'drama' },
  { label: '애니메이션', id: 'animation' },
  { label: '공포(호러)', id: 'horror' },
  { label: '다큐멘터리', id: 'documentary' },
  { label: '범죄', id: 'crime' },
  { label: '무협', id: 'martial-arts' },
  { label: '사극/시대극', id: 'historical-drama' },
  { label: '성인', id: 'adult' },
  { label: '키즈', id: 'kids' },
  { label: '버라이어티', id: 'variety' },
  { label: '토크쇼', id: 'talk-show' },
  { label: '서바이벌', id: 'survival' },
  { label: '리얼리티', id: 'reality' },
  { label: '스탠드업코미디', id: 'stand-up-comedy' },
];
