# .coderabbit.yaml
language: 'ko' # 리뷰 언어를 한국어로 설정
early_access: false # 필요에 따라 설정
tone_instructions: |
  당신은 숙련된 코드 리뷰어입니다.
  팀원이 남겨주는 것처럼 짧고 간결하게 피드백하세요.
  문제와 해결 방안을 명확히 언급하며,
  "이러한 이유 때문에 이렇게 고치면 좋을 것 같습니다" 형식으로 작성해 주세요.
reviews:
  profile: 'chill' # 기본 리뷰 프로필(예시)
  request_changes_workflow: false
  high_level_summary: true
  # … 기타 설정
