import { TicketComponent } from '@/types/recommend/TicketComponent';

export const dummyMovies: TicketComponent[] = [
  {
    contentId: 1,
    title: '쿵푸팬더 4',
    description:
      '용의 전사로 거듭난 포는 평화의 계곡의 영적 지도자가 되라는 명을 받는다. 하지만 새로운 적 카멜레온이 나타나 과거의 모든 악역들을 되살리려 하자, 포는 새로운 동료와 함께 이에 맞서야 한다.',
    posterUrl: '/poster.webp',
    backdropUrl: '/snapshot.webp',
    openDate: '2024년 3월 28일',
    runningTime: 94,
    episode: 1,
    rating: '전체관람가',
    categories: {
      category: '영화',
      genres: ['애니메이션', '액션'],
    },
    directors: ['마이크 미첼'],
    platforms: ['넷플릭스', '디즈니+'],
  },
  {
    contentId: 2,
    title: '듄: 파트 2',
    description:
      '아트레이데스 가문의 후계자 폴은 사막 행성 아라키스에서 프레멘족과 함께 황제와 하코넨 가문에 맞서 싸운다. 그는 자신의 운명과 우주의 미래를 결정짓는 선택의 기로에 서게 된다.',
    posterUrl: '/poster.webp',
    backdropUrl: '/snapshot.webp',
    openDate: '2024년 2월 28일',
    runningTime: 166,
    episode: 1,
    rating: '12세이상관람가',
    categories: {
      category: '영화',
      genres: ['애니메이션', '액션'],
    },
    directors: ['드니 빌뇌브'],
    platforms: ['넷플릭스', '디즈니+'],
  },
  {
    contentId: 3,
    title: '오펜하이머',
    description:
      '미국의 이론물리학자 로버트 오펜하이머가 원자폭탄 개발 프로젝트인 맨해튼 계획을 주도하며 겪는 내적 갈등과 역사적 순간들을 그린 작품.',
    posterUrl: '/poster.webp',
    backdropUrl: '/snapshot.webp',
    openDate: '2023년 8월 15일',
    runningTime: 180,
    episode: 1,
    rating: '15세이상관람가',
    categories: {
      category: '영화',
      genres: ['애니메이션', '액션'],
    },
    directors: ['크리스토퍼 놀란'],
    platforms: ['넷플릭스', '디즈니+'],
  },
  {
    contentId: 4,
    title: '스파이더맨: 어크로스 더 유니버스',
    description:
      '마일스 모랄레스가 다양한 차원의 스파이더맨들과 함께 멀티버스를 위협하는 새로운 적에 맞서는 모험을 그린 애니메이션.',
    posterUrl: '/poster.webp',
    backdropUrl: '/snapshot.webp',
    openDate: '2023년 6월 21일',
    runningTime: 140,
    episode: 1,
    rating: '12세이상관람가',
    categories: {
      category: '영화',
      genres: ['애니메이션', '액션'],
    },
    directors: ['호아킴 도스 산토스'],
    platforms: ['넷플릭스', '디즈니+'],
  },
  {
    contentId: 5,
    title: '존 윅 4',
    description:
      '최고 테이블에서 벗어나기 위해 옛 친구와 치명적인 적들을 상대로 전 세계를 무대로 펼치는 존 윅의 마지막 전쟁.',
    posterUrl: '/poster.webp',
    backdropUrl: '/snapshot.webp',
    openDate: '2023년 3월 22일',
    runningTime: 169,
    episode: 1,
    rating: '청소년관람불가',
    categories: {
      category: '영화',
      genres: ['애니메이션', '액션'],
    },
    directors: ['채드 스타헬스키'],
    platforms: ['넷플릭스', '디즈니+'],
  },
  {
    contentId: 6,
    title: '가디언즈 오브 갤럭시 Vol.3',
    description:
      '로켓의 과거가 밝혀지면서 가디언즈 팀이 그를 구하기 위해 위험한 미션에 나서는 감동적인 마지막 모험.',
    posterUrl: '/poster.webp',
    backdropUrl: '/snapshot.webp',
    openDate: '2023년 5월 3일',
    runningTime: 150,
    episode: 1,
    rating: '12세이상관람가',
    categories: {
      category: '영화',
      genres: ['애니메이션', '액션'],
    },
    directors: ['제임스 건'],
    platforms: ['넷플릭스', '디즈니+'],
  },
  {
    contentId: 7,
    title: '인디아나 존스: 운명의 다이얼',
    description:
      '은퇴를 앞둔 인디아나 존스가 시간을 조작할 수 있는 고대 유물을 둘러싸고 벌이는 마지막 모험.',
    posterUrl: '/poster.webp',
    backdropUrl: '/snapshot.webp',
    openDate: '2023년 6월 28일',
    runningTime: 154,
    episode: 1,
    rating: '12세이상관람가',
    categories: {
      category: '영화',
      genres: ['애니메이션', '액션'],
    },
    directors: ['제임스 맨골드'],
    platforms: ['넷플릭스', '디즈니+'],
  },
  {
    contentId: 8,
    title: '미션 임파서블: 데드 레코닝',
    description:
      '인공지능이 통제 불능 상태가 되면서 이단 헌트와 IMF 팀이 인류의 미래를 구하기 위해 나서는 액션 스릴러.',
    posterUrl: '/poster.webp',
    backdropUrl: '/snapshot.webp',
    openDate: '2023년 7월 12일',
    runningTime: 163,
    episode: 1,
    rating: '12세이상관람가',
    categories: {
      category: '영화',
      genres: ['애니메이션', '액션'],
    },
    directors: ['크리스토퍼 맥쿼리'],
    platforms: ['넷플릭스', '디즈니+'],
  },
  {
    contentId: 9,
    title: '트랜스포머: 비스트의 서막',
    description:
      '1990년대 브루클린을 배경으로 오토봇과 맥시멀이 테러콘과 프레데콘에 맞서 지구를 구하는 이야기.',
    posterUrl: '/poster.webp',
    backdropUrl: '/snapshot.webp',
    openDate: '2023년 6월 6일',
    runningTime: 127,
    episode: 1,
    rating: '12세이상관람가',
    categories: {
      category: '영화',
      genres: ['애니메이션', '액션'],
    },
    directors: ['스티븐 케이플 주니어'],
    platforms: ['넷플릭스', '디즈니+'],
  },
  {
    contentId: 10,
    title: '플래시',
    description:
      '과거를 바꾸기 위해 시간여행을 한 플래시가 예상치 못한 결과로 인해 다중우주에서 벌어지는 모험.',
    posterUrl: '/poster.webp',
    backdropUrl: '/snapshot.webp',
    openDate: '2023년 6월 14일',
    runningTime: 144,
    episode: 1,
    rating: '12세이상관람가',
    categories: {
      category: '영화',
      genres: ['애니메이션', '액션'],
    },
    directors: ['안드레스 무스키에티'],
    platforms: ['넷플릭스', '디즈니+'],
  },
];
